type 'a t

external create: unit -> 'a t = "btreemap_create"
external length: 'a t -> int = "btreemap_length"
external is_empty: 'a t -> bool = "btreemap_is_empty"
external clear: 'a t -> unit = "btreemap_clear"
external find_opt: 'a t -> string -> 'a option = "btreemap_find_opt"
external mem: 'a t -> string -> bool = "btreemap_mem"
external add: 'a t -> string -> 'a -> unit = "btreemap_add"
external remove: 'a t -> string -> unit = "btreemap_remove"
external iter: 'a t -> (string -> 'a -> unit) -> unit = "btreemap_iter"
external iter_range: 'a t -> string -> string -> (string -> 'a -> unit) -> unit = "btreemap_iter_range"
external iter_inclusive_range: 'a t -> string -> string -> (string -> 'a -> unit) -> unit = "btreemap_iter_inclusive_range"
external fold: 'a t -> (string -> 'a -> 'b -> 'b) -> 'b -> 'b = "btreemap_fold"
external exists: 'a t -> (string -> 'a -> bool) -> bool = "btreemap_exists"
external min_binding: 'a t -> (string * 'a) option = "btreemap_min_binding"
external max_binding: 'a t -> (string * 'a) option = "btreemap_max_binding"
external find_first_opt: 'a t -> string -> (string * 'a) option = "btreemap_find_first_opt"
external find_last_opt: 'a t -> string -> (string * 'a) option = "btreemap_find_last_opt"
external split_off_after: 'a t -> string -> 'a t = "btreemap_split_off_after"

