type t

external create: unit -> t = "btreemap_create"
external length: t -> int = "btreemap_length"
external is_empty: t -> bool = "btreemap_is_empty"
external clear: t -> unit = "btreemap_clear"
external find_opt: string -> t -> int64 option = "btreemap_find_opt"
external mem: string -> t -> bool = "btreemap_mem"
external add: string -> int64 -> t -> unit = "btreemap_add"
external update: string -> int64 -> t -> unit = "btreemap_update"
external xadd: string -> int64 -> t -> unit = "btreemap_xadd"
external remove: string -> t -> unit = "btreemap_remove"
external iter: (string -> int64 -> unit) -> t -> unit = "btreemap_iter"
external iter_range: string -> string -> (string -> int64 -> unit) -> t -> unit = "btreemap_iter_range"
external iter_inclusive_range: string -> string -> (string -> int64 -> unit) -> t -> unit = "btreemap_iter_inclusive_range"
external fold: (string -> int64 -> 'b -> 'b) -> t -> 'b -> 'b = "btreemap_fold"
external exists: (string -> int64 -> bool) -> t -> bool = "btreemap_exists"
external min_binding: t -> (string * int64) option = "btreemap_min_binding"
external max_binding: t -> (string * int64) option = "btreemap_max_binding"
external find_first_opt: string -> t -> (string * int64) option = "btreemap_find_first_opt"
external find_last_opt: string -> t -> (string * int64) option = "btreemap_find_last_opt"
external split_off_after: string -> t -> t = "btreemap_split_off_after"

